# Use root/example as user/password credentials
version: '3.7'

services:

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  tesseract:
    build:
      context: ./tesseract
      dockerfile: Dockerfile
    container_name: t4re-u194
    volumes:
      - ../data/:/home/work/data/
    tty: true

volumes:
  mongodata:
    driver: local
