# Use root/example as user/password credentials for mongoDB
version: '3.7'

services:

  mongo:
    image: mongo
    container_name: mongodb
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  tesseract:
    build:
      context: ./tesseract
      dockerfile: Dockerfile-tesseract5
    container_name: tesseract
    restart: on-failure
    volumes:
      - ../data/:/home/work/data/
    tty: true

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elastic
    environment:
      - node.name=elastic
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - nlp

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: http://elastic:9200
    container_name: kibana
    networks:
      - nlp
    ports:
      - 5601:5601
    depends_on:
      - elastic

  logstash:
    build:
      context: ./logstash
      dockerfile: Dockerfile
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: http://elastic:9200
    container_name: logstash
    networks:
      - nlp
    ports:
      - 5044:5044
    depends_on:
      - elastic

volumes:
  mongodata:
    driver: local
  elastic_data:
    driver: local

networks:
  nlp:
    driver: bridge